// <auto-generated />
namespace TaskManagerApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addproperdataannotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addproperdataannotations));
        
        string IMigrationMetadata.Id
        {
            get { return "202306051808107_add-proper-data-annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
